// app/images_sitemap.xml/route.ts
import { NextResponse } from "next/server";

type Page = {
  loc: string;
  lastmod?: string;
  changefreq?:
    | "always"
    | "hourly"
    | "daily"
    | "weekly"
    | "monthly"
    | "yearly"
    | "never";
  priority?: number;
  images?: string[];
};

const PAGES: Page[] = [
  {
    loc: "https://kogents.ai/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 1.0,
    images: [
      "https://kogents.ai/assets/img/erp-011.svg",
      "https://kogents.ai/assets/img/back-img.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fwhatsapp-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fphone-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fai-assistant-app.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fai-chatbot-agent.webp&w=1200&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fvoice-ai-agent.webp&w=1200&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fshopify-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fmessenger-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fstandalone-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fkiosk-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fshopify-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fai-chatbot-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fhome%2Fvoice-ai-agent.webp&w=828&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fmembers.png&w=1920&q=75",
      "https://kogents.ai/assets/img/agent-01.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-complaint-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fclient-call-log-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fsupport-satisfaction-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fsupport-request-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-support-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-service-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-review-ai-agent.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft1.png&w=256&q=75",
      "https://kogents.ai/assets/img/box-01.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft2.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft3.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft4.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft5.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft6.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Ft7.png&w=256&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fapp-section%2F5.png&w=384&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/calendly-ai-integration/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-calendly/banner.webp",
      "https://kogents.ai/assets/img/ai-calendly/1.svg",
      "https://kogents.ai/assets/img/ai-calendly/2.svg",
      "https://kogents.ai/assets/img/ai-calendly/3.svg",
      "https://kogents.ai/assets/img/ai-calendly/4.svg",
      "https://kogents.ai/assets/img/ai-calendly/5.svg",
      "https://kogents.ai/assets/img/ai-calendly/6.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-calendly%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-calendly%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-calendly%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-calendly%2F4.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-calendly/5.webp",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/microsoft-teams-agents/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-microsoft/banner.webp",
      "https://kogents.ai/assets/img/ai-microsoft/1.svg",
      "https://kogents.ai/assets/img/ai-microsoft/2.svg",
      "https://kogents.ai/assets/img/ai-microsoft/3.svg",
      "https://kogents.ai/assets/img/ai-microsoft/4.svg",
      "https://kogents.ai/assets/img/ai-microsoft/5.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F4.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-microsoft/5.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fclient-call-log-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fsupport-satisfaction-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fsupport-request-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fmedical-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-support-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fcustomer-service-ai-agent.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fai-recruiting-assistant.webp&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam-slider%2Fai-automation-agency.webp&w=1080&q=75",
      "https://kogents.ai/assets/img/ai-agent-dashboard/5.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/6.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/7.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/8.svg",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/ai-telegram-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-telegram/banner.webp",
      "https://kogents.ai/assets/img/ai-telegram/1.svg",
      "https://kogents.ai/assets/img/ai-telegram/2.svg",
      "https://kogents.ai/assets/img/ai-telegram/3.svg",
      "https://kogents.ai/assets/img/ai-telegram/4.svg",
      "https://kogents.ai/assets/img/ai-telegram/5.svg",
      "https://kogents.ai/assets/img/ai-telegram/6.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F5.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-telegram%2F6.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-telegram/7.webp",
    ],
  },
  {
    loc: "https://kogents.ai/contact-us/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/phone.svg",
      "https://kogents.ai/assets/img/address.svg",
      "https://kogents.ai/assets/img/facebook.svg",
      "https://kogents.ai/assets/img/linkedin.svg",
      "https://kogents.ai/assets/img/twitter.svg",
      "https://kogents.ai/assets/img/youtube.svg",
      "https://kogents.ai/assets/img/instagram.svg",
      "https://kogents.ai/assets/img/pinterest.svg",
      "https://kogents.ai/assets/img/tiktok.svg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/_next/image/?url=https%3A%2F%2Fportal.kogents.ai%2Fwp-content%2Fuploads%2F2025%2F11%2Fai-automation-platforms.jpg&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=https%3A%2F%2Fportal.kogents.ai%2Fwp-content%2Fuploads%2F2025%2F11%2Fai-automation-consultant.jpg&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/security/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: ["https://kogents.ai/assets/img/badegs.webp"],
  },
  {
    loc: "https://kogents.ai/platforms/zendesk-ai-integration/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-zendesk/banner.webp",
      "https://kogents.ai/assets/img/ai-zendesk/1.svg",
      "https://kogents.ai/assets/img/ai-zendesk/2.svg",
      "https://kogents.ai/assets/img/ai-zendesk/3.svg",
      "https://kogents.ai/assets/img/ai-zendesk/44.svg",
      "https://kogents.ai/assets/img/ai-zendesk/5.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F5.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-zendesk%2F6.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/viber-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-viber/banner.webp",
      "https://kogents.ai/assets/img/ai-viber/1.svg",
      "https://kogents.ai/assets/img/ai-viber/2.svg",
      "https://kogents.ai/assets/img/ai-viber/3.svg",
      "https://kogents.ai/assets/img/ai-viber/4.svg",
      "https://kogents.ai/assets/img/ai-viber/5.svg",
      "https://kogents.ai/assets/img/ai-viber/6.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-viber%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-viber%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-viber%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-viber%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-viber%2F5.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-viber/6.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-agent-dashboard/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-agent-dashboard/banner.webp",
      "https://kogents.ai/assets/img/ai-agent-dashboard/1.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/2.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/3.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/4.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/5.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/6.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/7.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/8.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/9.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/define-metrics.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-agent-event-planner/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-agent-event-planner/banner.webp",
      "https://kogents.ai/assets/img/ai-agent-event-planner/1.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/2.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/3.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/4.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/5.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/6.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/7.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/8.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/9.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/10.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/11.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/12.svg",
      "https://kogents.ai/assets/img/ai-agent-event-planner/identify-pain-points.webp",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/ai-agent-for-messenger/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/messenger-banner.webp",
      "https://kogents.ai/assets/img/ai-messenger/1.svg",
      "https://kogents.ai/assets/img/ai-messenger/2.svg",
      "https://kogents.ai/assets/img/ai-messenger/3.svg",
      "https://kogents.ai/assets/img/ai-messenger/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-messenger%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-messenger%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-messenger%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-messenger%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-messenger%2F5.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-messenger/6.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/survey-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/survey-ai-agent/banner.webp",
      "https://kogents.ai/assets/img/survey-ai-agent/1.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/2.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/3.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/4.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/5.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/6.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/7.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/8.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/9.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/10.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/11.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/12.svg",
      "https://kogents.ai/assets/img/survey-ai-agent/1.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/healthcare-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-healthcare/banner.webp",
      "https://kogents.ai/assets/img/ai-healthcare/1.svg",
      "https://kogents.ai/assets/img/ai-healthcare/2.svg",
      "https://kogents.ai/assets/img/ai-healthcare/3.svg",
      "https://kogents.ai/assets/img/ai-healthcare/4.svg",
      "https://kogents.ai/assets/img/ai-healthcare/5.svg",
      "https://kogents.ai/assets/img/ai-healthcare/6.svg",
      "https://kogents.ai/assets/img/ai-healthcare/7.svg",
      "https://kogents.ai/assets/img/ai-healthcare/8.svg",
      "https://kogents.ai/assets/img/ai-healthcare/9.svg",
      "https://kogents.ai/assets/img/ai-healthcare/identify-pain-points-in-care-delivery.webp",
    ],
  },
  {
    loc: "https://kogents.ai/about-us/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fmembers.png&w=1080&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F1.png&w=640&q=75",
      "https://kogents.ai/assets/img/icons/linkedin.svg",
      "https://kogents.ai/assets/img/icons/x.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F2.png&w=640&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F3.png&w=640&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F4.png&w=640&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F5.png&w=640&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fteam%2F6.png&w=640&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/whatsapp-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-whatsapp/whatsapp-banner.webp",
      "https://kogents.ai/assets/img/ai-whatsapp/1.svg",
      "https://kogents.ai/assets/img/ai-whatsapp/2.svg",
      "https://kogents.ai/assets/img/ai-whatsapp/3.svg",
      "https://kogents.ai/assets/img/ai-whatsapp/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-whatsapp%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-whatsapp%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-whatsapp%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-whatsapp%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-whatsapp%2F5.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-teacher-assistant/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-teacher-assistant/banner.webp",
      "https://kogents.ai/assets/img/ai-teacher-assistant/1.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/2.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/3.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/4.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/5.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/6.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/7.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/8.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/9.svg",
      "https://kogents.ai/assets/img/ai-teacher-assistant/define-teaching-goals.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-agent-for-hr/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-agent-for-hr/banner.webp",
      "https://kogents.ai/assets/img/ai-agent-for-hr/1.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/2.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/3.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/4.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/5.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/6.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/7.svg",
      "https://kogents.ai/assets/img/ai-agent-for-hr/8.svg",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-agent-for-marketing/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-agent-for-marketing/banner.webp",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/1.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/2.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/3.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/4.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/5.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/6.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/7.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/8.svg",
      "https://kogents.ai/assets/img/ai-agent-for-marketing/9.svg",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/jira-ai-integration/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-jira/banner.webp",
      "https://kogents.ai/assets/img/ai-jira/1.svg",
      "https://kogents.ai/assets/img/ai-jira/2.svg",
      "https://kogents.ai/assets/img/ai-jira/3.svg",
      "https://kogents.ai/assets/img/ai-jira/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-jira%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-jira%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-jira%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-jira%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-jira%2F5.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/hubspot-ai-integration/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-hubspot/banner.webp",
      "https://kogents.ai/assets/img/ai-hubspot/1.svg",
      "https://kogents.ai/assets/img/ai-hubspot/2.svg",
      "https://kogents.ai/assets/img/ai-hubspot/3.svg",
      "https://kogents.ai/assets/img/ai-hubspot/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-hubspot%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-hubspot%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-hubspot%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-hubspot%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-hubspot%2F5.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-hubspot/6.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-agent-for-education/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-agent-for-education/banner.webp",
      "https://kogents.ai/assets/img/ai-agent-for-education/1.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/2.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/3.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/4.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/5.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/6.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/7.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/8.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/9.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/10.svg",
      "https://kogents.ai/assets/img/ai-agent-for-education/identify_learning_gaps.webp",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/shopify-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-shopify/banner.webp",
      "https://kogents.ai/assets/img/ai-shopify/1.svg",
      "https://kogents.ai/assets/img/ai-shopify/2.svg",
      "https://kogents.ai/assets/img/ai-shopify/3.svg",
      "https://kogents.ai/assets/img/ai-shopify/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-shopify%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-shopify%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-shopify%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-shopify%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-shopify%2F5.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/slack-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-slack/banner.webp",
      "https://kogents.ai/assets/img/ai-slack/1.svg",
      "https://kogents.ai/assets/img/ai-slack/2.svg",
      "https://kogents.ai/assets/img/ai-slack/3.svg",
      "https://kogents.ai/assets/img/ai-slack/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-slack%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-slack%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-slack%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-slack%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-slack%2F5.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-slack/6.webp",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/line-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/ai-microsoft/banner.webp",
      "https://kogents.ai/assets/img/ai-microsoft/1.svg",
      "https://kogents.ai/assets/img/ai-microsoft/2.svg",
      "https://kogents.ai/assets/img/ai-microsoft/3.svg",
      "https://kogents.ai/assets/img/ai-microsoft/4.svg",
      "https://kogents.ai/assets/img/ai-microsoft/5.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-microsoft%2F4.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-agent-dashboard/define-metrics.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/customer-service-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/customer-service-ai-agents/banner.webp",
      "https://kogents.ai/assets/img/customer-service-ai-agents/1.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/2.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/3.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/4.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/5.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/6.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/7.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/8.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/9.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/10.svg",
      "https://kogents.ai/assets/img/customer-service-ai-agents/identify-pain-points-in-service-delivery.webp",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.9,
    images: [
      "https://kogents.ai/assets/img/icons/shopify.svg",
      "https://kogents.ai/assets/img/icons/calendly.png",
      "https://kogents.ai/assets/img/icons/sunshine.svg",
      "https://kogents.ai/assets/img/icons/intercom.svg",
      "https://kogents.ai/assets/img/icons/zendesk.svg",
      "https://kogents.ai/assets/img/icons/ai-voice-agent.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/5.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/6.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/7.svg",
      "https://kogents.ai/assets/img/ai-agent-dashboard/8.svg",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-automation-agency/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/ai-automation-agency/banner.webp",
      "https://kogents.ai/assets/img/ai-automation-agency/1.svg",
      "https://kogents.ai/assets/img/ai-automation-agency/2.svg",
      "https://kogents.ai/assets/img/ai-automation-agency/3.svg",
      "https://kogents.ai/assets/img/ai-automation-agency/4.svg",
      "https://kogents.ai/assets/img/ai-automation-agency/5.svg",
      "https://kogents.ai/assets/img/ai-automation-agency/6.svg",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/intercom-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/ai-intercom/banner.webp",
      "https://kogents.ai/assets/img/ai-intercom/1.svg",
      "https://kogents.ai/assets/img/ai-intercom/2.svg",
      "https://kogents.ai/assets/img/ai-intercom/3.svg",
      "https://kogents.ai/assets/img/ai-intercom/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-intercom%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-intercom%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-intercom%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-intercom%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-intercom%2F5.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/instagram-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/ai-instagram/banner.webp",
      "https://kogents.ai/assets/img/ai-instagram/1.svg",
      "https://kogents.ai/assets/img/ai-instagram/2.svg",
      "https://kogents.ai/assets/img/ai-instagram/3.svg",
      "https://kogents.ai/assets/img/ai-instagram/4.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-instagram%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-instagram%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-instagram%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-instagram%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-instagram%2F5.webp&w=1920&q=75",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/ai-recruiting-assistant/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/ai-recruiting-assistant/banner.webp",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/1.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/2.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/3.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/4.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/5.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/6.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/7.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/8.svg",
      "https://kogents.ai/assets/img/ai-recruiting-assistant/9.svg",
    ],
  },
  {
    loc: "https://kogents.ai/platforms/sunshine-conversation-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/ai-sunshine/banner.webp",
      "https://kogents.ai/assets/img/ai-sunshine/1.svg",
      "https://kogents.ai/assets/img/ai-sunshine/2.svg",
      "https://kogents.ai/assets/img/ai-sunshine/3.svg",
      "https://kogents.ai/assets/img/ai-sunshine/4.svg",
      "https://kogents.ai/assets/img/ai-sunshine/5.svg",
      "https://kogents.ai/assets/img/ai-sunshine/6.svg",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F1.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F2.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F3.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F4.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F5.webp&w=1920&q=75",
      "https://kogents.ai/_next/image/?url=%2Fassets%2Fimg%2Fai-sunshine%2F6.webp&w=1920&q=75",
      "https://kogents.ai/assets/img/ai-sunshine/7.webp",
    ],
  },
  {
    loc: "https://kogents.ai/solutions/medical-ai-agent/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://kogents.ai/assets/img/medical-ai-agent/bannerr.webp",
      "https://kogents.ai/assets/img/medical-ai-agent/b1.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/b2.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/b3.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/b4.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w5.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w6.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w7.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w8.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w9.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w10.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w11.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/w12.svg",
      "https://kogents.ai/assets/img/medical-ai-agent/1.webp",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/shopify-ai-customer-support/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.8,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/11/shopify-ai-customer-support.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/prioritize-shopify-ai-customer-support-scaled.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/shopify-inbox-ai-vs-third-party-ai-scaled.jpg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/enterprise-ai-development/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.7,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/11/enterprise-ai-development.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/custom-enterprise-ai-development-scaled.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/advanced-enterprise-ai-development-scaled.jpg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/ai-governance-and-compliance/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.6,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-governance-and-compliance.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-governance-and-compliance-frameworks-scaled.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/how-leaders-can-drive-governance-from-the-top-down-scaled.jpg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/ai-integration-for-legacy-systems/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.6,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-integration-for-legacy-systems.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-integration-for-legacy-system-scaled.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-integration-for-legacy-systems-in-regulated-industries-scaled.jpg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/ai-driven-customer-support/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.5,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-driven-customer-support.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/ai-driven-customer-support-meets-the-metaverse-scaled.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/11/reality-of-ai-driven-customer-support-scaled.jpg",
    ],
  },
  {
    loc: "https://kogents.ai/blogs/how-to-create-an-ai-agent-from-scratch/",
    lastmod: "2025-11-21",
    changefreq: "daily",
    priority: 0.5,
    images: [
      "https://portal.kogents.ai/wp-content/uploads/2025/10/how-to-create-an-ai-agent-from-scratch.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/10/know-how-to-create-an-ai-agent-from-scratch-2048x967-side3.jpg",
      "https://portal.kogents.ai/wp-content/uploads/2025/10/frameworks-to-build-ai-agents-from-scratch-2048x1442-side4.jpg",
    ],
  },
];

function xmlEscape(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function imageTag(url: string): string {
  return `    <image:image>\n      <image:loc>${xmlEscape(url)}</image:loc>\n    </image:image>`;
}

function urlBlock(p: Page): string {
  const out: string[] = [];
  out.push("  <url>");
  out.push(`    <loc>${xmlEscape(p.loc)}</loc>`);
  if (p.lastmod) out.push(`    <lastmod>${xmlEscape(p.lastmod)}</lastmod>`);
  if (p.changefreq) out.push(`    <changefreq>${p.changefreq}</changefreq>`);
  if (typeof p.priority === "number")
    out.push(`    <priority>${p.priority.toFixed(1)}</priority>`);
  if (p.images?.length) for (const u of p.images) out.push(imageTag(u));
  out.push("  </url>");
  return out.join("\n");
}

function buildXml(pages: Page[]): string {
  const head = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">`;
  const body = pages.map(urlBlock).join("\n");
  const tail = `</urlset>`;
  return [head, body, tail].join("\n");
}

export async function GET() {
  const xml = buildXml(PAGES);
  return new NextResponse(xml, {
    status: 200,
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control":
        "public, s-maxage=3600, max-age=3600, stale-while-revalidate=300",
    },
  });
}
