import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import "./css/aos.css";/
// import "./css/output.css";
// import "./css/ipad-style.css";
// import "./css/ipadpro-style.css";
// import "./css/bootstrap.css";
// import "./css/styles.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="assets/css/aos.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/css/output.css" />
        <link rel="stylesheet" href="assets/css/ipad-style.css" />
        <link rel="stylesheet" href="assets/css/ipadpro-style.css" />
        <link rel="stylesheet" href="assets/css/bootstrap.css" />
        <link rel="stylesheet" href="assets/css/styles.css" />
      </head>
      <body
        className="relative overflow-x-hidden font-normal bg-b-900"
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
