import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Kogents Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        <link href="assets/css/aos.css" rel="stylesheet" />
        <link rel="stylesheet" href="assets/css/output.css" />
        <link rel="stylesheet" href="assets/css/ipad-style.css" />
        <link rel="stylesheet" href="assets/css/ipadpro-style.css" />
        <link rel="stylesheet" href="assets/css/bootstrap.css" />
        <link rel="stylesheet" href="assets/css/styles.css" />
      </head>
      <body
        className="relative overflow-x-hidden font-normal bg-b-900"
      >
        <Header />
        {children}
        <Footer />
      </body>
      <script>
        AOS.init();
      </script>
    </html>
  );
}
